project:
  type: book
  preview:
    browser: true
    watch-inputs: true
    navigate: true

resources:
  - slides
  - pdf
  - robots.txt

book:
  title: "Synthetic Relativity"
  author: "Adrian R. Pearce"
  chapters:
    - index.qmd
    - talk.qmd
    - appendix.qmd
  site-url: https://adrianpearce.github.io/synthetic-relativity/

format:
  html:
    smooth-scroll: true
    html-math-method: mathjax
    theme: cosmo
    css: book.css     # overrides live here
    toc: true
    toc-location: left      # “mini-book” feel in one page
    toc-depth: 1
    number-sections: false

