project:
  type: website
  output-dir: slides
  render:
    - introduction.qmd

format:
  revealjs:
    theme: solarized
    css: slides.css
    transition: slide
    slide-number: true
    toc: true
    toc-depth: 1
    center: false
    html-math-method: mathjax
    lib-dir: site_libs
    plugins:
      - chalkboard
    chalkboard: true
    oembed: true

include-after-body:
  - math-retypeset.js

