---
title: "Introduction"
author: 
  - name: Adrian R. Pearce
    email: adrianrp@unimelb.edu.au
    orcid: 0000-0003-0089-8474
    url: https://findanexpert.unimelb.edu.au/profile/14397-adrian-pearce
    affiliations:
      - ref: unimelb

affiliations:
  - id: unimelb
    name: The University of Melbourne
    department: School of Computing and Information Systems
    address: Parkville
    city: Melbourne
    region: VIC
    country: AU
    postal-code: 3010
---


# Synthetic Relativity: Tri-modality and the Fixpoint Semantics of the Logical Observer

## Author

Professor Adrian R. Pearce, School of Computing and Information Systems, The University of Melbourne

## Abstract

There has been a rich history of using extensions to the Situation Calculus, such as variations of the $\mu$-calculus, to compute least and greatest fixpoints for solving problems like strategy synthesis and verifying temporally extended properties. Traditionally, these approaches have relied on the encoding of static, global Basic Action Theories. Here, we show how problems of this nature can more generally be thought of as logical self-reflection, involving both inference duality and categorical duality. We introduce a relativistic framework founded on Stone duality for the computation of greatest and least fixpoints, leading to a more integrated approach not only for solving existing problems, but potentially for progressing basic action theories themselves-yielding *self-transcending action theories*.

To formalise self-reflection as a dynamic, computationally tractable process, this talk introduces Synthetic Relativity, presenting a new and unique set of structural axioms and corresponding mathematical theorems. We show how these foundational axioms can utilise a Relativistic version of Domain Theory in Logical Form (R-DTLF) to establish a trimodal logic, natively dividing computation into an inductive syntactic accumulator ($\mathrm{RDo}$), a coinductive semantic observer ($\mathrm{ODo}$), and a relativistic progression engine ($\mathrm{PDo}$). Through Semantic Realisation, we demonstrate how bottom-up syntactic proof traces and top-down semantic invariants mathematically lock at a state of Algebraic Compactness ($\mu = \nu$). This topological resolution permits a categorical Change of Base via a Transitivity Axiom, allowing an autonomous agent to dynamically shift its baseline reference frame. Finally, via Topological Booleanization, we illustrate how the semantic observer can act as a logic compiler, mathematically deducing hidden structural invariants and compiling them into classical Successor State Axioms (SSAs).

## Biography 

Adrian R. Pearce is a Professor and Deputy Head of School (Engagement) in the School of Computer Science and Information Systems at the University of Melbourne. 

